# Generated by Django 6.0.2 on 2026-02-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("data_nascimento", models.DateField()),
                ("endereco", models.CharField(max_length=255)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimentos",
                        to="core.paciente",
                    ),
                ),
            ],
        ),
    ]
