# Generated by Django 6.0.2 on 2026-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
