# Generated by Django 6.0.2 on 2026-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_paciente_data_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedimento",
            name="data",
            field=models.DateField(),
        ),
    ]
