# Generated by Django 6.0.2 on 2026-03-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_procedimento_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedimento",
            name="observacoes",
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="descricao",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
