# Generated by Django 6.0.2 on 2026-03-05 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_procedimento_observacoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procedimento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
