# Generated by Django 6.0.2 on 2026-03-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_procedimento_criado_em_procedimento_observacoes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedimento",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="procedimento",
            name="observacoes",
        ),
        migrations.AlterField(
            model_name="paciente",
            name="endereco",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="core.paciente",
                    ),
                ),
            ],
        ),
    ]
