# Generated by Django 6.0.2 on 2026-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_procedimento_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
