# Generated by Django 6.0.2 on 2026-03-10 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_paciente_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="ArquivoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("raiox", "Raio-X"),
                            ("foto", "Foto"),
                            ("pdf", "PDF"),
                            ("documento", "Documento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="pacientes/arquivos/")),
                ("descricao", models.TextField(blank=True, null=True)),
                ("enviado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos",
                        to="core.paciente",
                    ),
                ),
            ],
        ),
    ]
