# Generated by Django 6.0.2 on 2026-03-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_paciente_nome_alter_paciente_telefone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdontogramaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dente",
                    models.CharField(
                        choices=[
                            ("18", "18"),
                            ("17", "17"),
                            ("16", "16"),
                            ("15", "15"),
                            ("14", "14"),
                            ("13", "13"),
                            ("12", "12"),
                            ("11", "11"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("48", "48"),
                            ("47", "47"),
                            ("46", "46"),
                            ("45", "45"),
                            ("44", "44"),
                            ("43", "43"),
                            ("42", "42"),
                            ("41", "41"),
                            ("31", "31"),
                            ("32", "32"),
                            ("33", "33"),
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                            ("38", "38"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saudavel", "Saudável"),
                            ("carie", "Cárie"),
                            ("restauracao", "Restauração"),
                            ("canal", "Canal"),
                            ("extracao", "Extração"),
                            ("implante", "Implante"),
                            ("ausente", "Ausente"),
                            ("outro", "Outro"),
                        ],
                        default="saudavel",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odontograma",
                        to="core.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["dente"],
                "unique_together": {("paciente", "dente")},
            },
        ),
    ]
