# Generated by Django 6.0.2 on 2026-03-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_odontogramaitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dentista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cro", models.CharField(blank=True, max_length=50)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("especialidade", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="consulta",
            name="dentista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas",
                to="core.dentista",
            ),
        ),
    ]
