# Generated by Django 6.0.2 on 2026-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dentista_consulta_dentista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentista',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='dentista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dentista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='cro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
