# Generated by Django 6.0.2 on 2026-03-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_dentista_especialidade_dentista_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="dentista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedimentos",
                to="core.dentista",
            ),
        ),
    ]
