# Generated by Django 6.0.2 on 2026-03-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_sala_consulta_sala"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="duracao_minutos",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "30 minutos"),
                    (60, "60 minutos"),
                    (90, "90 minutos"),
                    (120, "120 minutos"),
                ],
                default=60,
            ),
        ),
    ]
