# Generated by Django 6.0.2 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_consulta_duracao_minutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor cobrado pela consulta/procedimento",
                max_digits=10,
            ),
        ),
    ]
